#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat <<'EOF'
expand-includes.sh — simple textual include expander

USAGE:
  expand-includes.sh <input-file>
  expand-includes.sh -h | --help

DESCRIPTION:
  Reads <input-file> and writes the expanded result to stdout.

  Lines matching the following form are replaced by the contents
  of the referenced file:

      include: "path/to/file.yml.in" # optional comment

  Rules:
    - The filepath MUST be in double quotes.
    - Leading whitespace (spaces and/or tabs) is preserved and applied
      to every line of the included file.
    - Trailing comments starting with '#' are ignored.
    - Whitespace around 'include:' and the filename is ignored.
    - Included files may themselves contain include: directives.
    - Expansion is purely textual; no YAML parsing is performed.

EOF
}

expand_file() {
    local file="$1"

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Remove trailing comments for matching (keep original for output)
        local stripped="${line%%#*}"

        # Match YAML include line:
        #
        #   <indent>include: "path"
        #
        if [[ "$stripped" =~ ^([[:space:]]*)include[[:space:]]*:[[:space:]]*\"([^\"]+)\"[[:space:]]*$ ]]; then
            local indent="${BASH_REMATCH[1]}"
            local include_file="${BASH_REMATCH[2]}"

            if [[ ! -f "$include_file" ]]; then
                echo "ERROR: included file not found: $include_file" >&2
                return 1
            fi

            # Recursively expand included file (no subshells)
            if ! mapfile -t inc_lines < <(expand_file "$include_file"); then
                return 1
            fi

            for inc_line in "${inc_lines[@]}"; do
                printf "%s%s\n" "$indent" "$inc_line"
            done

        else
            echo "$line"
        fi
    done < "$file"
}


# ---- main ----

if [[ $# -ne 1 ]]; then
    print_help >&2
    exit 1
fi

case "$1" in
    -h|--help)
        print_help
        exit 0
        ;;
esac

printf "# Warning: generated file, do not edit. Generated by '%s %s'\n" "$0" "$*"

expand_file "$1"
