#!/bin/bash

# This script creates the BLACKLIST file for the 'v5.15.8-lts-lgpl' Qt branch.

cat << EOF > tests/auto/network/ssl/qsslsocket/BLACKLIST
[simpleConnect:WithoutProxy]
ci
[simpleConnectWithIgnore:WithoutProxy]
ci
[connectToHostEncrypted:WithoutProxy]
ci
[connectToHostEncryptedWithVerificationPeerName:WithoutProxy]
ci
[sessionCipher:WithoutProxy]
ci
[sessionCipher:WithSocks5Proxy]
ci
[sessionCipher:WithSocks5ProxyAuth]
ci
[sessionCipher:WithHttpProxy]
ci
[sessionCipher:WithHttpProxyBasicAuth]
ci
[protocol:WithoutProxy]
ci
[protocolServerSide:WithoutProxy:tls1.0-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1ssl3-tls1ssl3]
ci
[protocolServerSide:WithoutProxy:any-any]
ci
[protocolServerSide:WithoutProxy:secure-secure]
ci
[protocolServerSide:WithoutProxy:tls1-tls1ssl3]
ci
[protocolServerSide:WithoutProxy:tls1.0-secure]
ci
[protocolServerSide:WithoutProxy:tls1.0-any]
ci
[protocolServerSide:WithoutProxy:tls1ssl3-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1ssl3-secure]
ci
[protocolServerSide:WithoutProxy:tls1ssl3-any]
ci
[protocolServerSide:WithoutProxy:secure-tls1.0]
ci
[protocolServerSide:WithoutProxy:secure-tls1ssl3]
ci
[protocolServerSide:WithoutProxy:secure-any]
ci
[protocolServerSide:WithoutProxy:tls1.0orlater-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1.0orlater-tls1.1]
ci
[protocolServerSide:WithoutProxy:tls1.0orlater-tls1.2]
ci
[protocolServerSide:WithoutProxy:tls1.0orlater-tls1.3]
ci
[protocolServerSide:WithoutProxy:tls1.1orlater-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1.1orlater-tls1.1]
ci
[protocolServerSide:WithoutProxy:tls1.1orlater-tls1.2]
ci
[protocolServerSide:WithoutProxy:tls1.1orlater-tls1.3]
ci
[protocolServerSide:WithoutProxy:tls1.2orlater-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1.2orlater-tls1.1]
ci
[protocolServerSide:WithoutProxy:tls1.2orlater-tls1.2]
ci
[protocolServerSide:WithoutProxy:tls1.2orlater-tls1.3]
ci
[protocolServerSide:WithoutProxy:tls1.3orlater-tls1.0]
ci
[protocolServerSide:WithoutProxy:tls1.3orlater-tls1.1]
ci
[protocolServerSide:WithoutProxy:tls1.3orlater-tls1.2]
ci
[protocolServerSide:WithoutProxy:tls1.3orlater-tls1.3]
ci
[protocolServerSide:WithoutProxy:any-tls1.0]
ci
[protocolServerSide:WithoutProxy:any-tls1ssl3]
ci
[protocolServerSide:WithoutProxy:any-secure]
ci
[serverCipherPreferences:WithoutProxy]
ci
[setLocalCertificateChain:WithoutProxy]
ci
[setSocketDescriptor:WithoutProxy]
ci
[setSslConfiguration:WithoutProxy:set-root-cert]
ci
[setSslConfiguration:WithoutProxy:secure]
ci
[waitForConnectedEncryptedReadyRead:WithoutProxy]
ci
[waitForConnectedEncryptedReadyRead:WithSocks5Proxy]
ci
[waitForConnectedEncryptedReadyRead:WithSocks5ProxyAuth]
ci
[waitForConnectedEncryptedReadyRead:WithHttpProxy]
ci
[waitForConnectedEncryptedReadyRead:WithHttpProxyBasicAuth]
ci
[spontaneousWrite:WithoutProxy]
ci
[setReadBufferSize:WithoutProxy]
ci
[waitForMinusOne:WithoutProxy]
ci
[verifyMode:WithoutProxy]
ci
[resetProxy:WithoutProxy]
ci
[abortOnSslErrors:WithoutProxy]
ci
[readFromClosedSocket:WithoutProxy]
ci
[blacklistedCertificates:WithoutProxy]
ci
[resume:WithoutProxy:DoNotIgnoreErrors]
ci
[resume:WithoutProxy:ignoreAllErrors]
ci
[resume:WithoutProxy:ignoreSpecificErrors-Wrong]
ci
[resume:WithoutProxy:ignoreSpecificErrors-Right]
ci
[resume:WithSocks5Proxy:DoNotIgnoreErrors]
ci
[resume:WithSocks5Proxy:ignoreAllErrors]
ci
[resume:WithSocks5Proxy:ignoreSpecificErrors-Wrong]
ci
[resume:WithSocks5Proxy:ignoreSpecificErrors-Right]
ci
[resume:WithSocks5ProxyAuth:DoNotIgnoreErrors]
ci
[resume:WithSocks5ProxyAuth:ignoreAllErrors]
ci
[resume:WithSocks5ProxyAuth:ignoreSpecificErrors-Wrong]
ci
[resume:WithSocks5ProxyAuth:ignoreSpecificErrors-Right]
ci
[resume:WithHttpProxy:DoNotIgnoreErrors]
ci
[resume:WithHttpProxy:ignoreAllErrors]
ci
[resume:WithHttpProxy:ignoreSpecificErrors-Wrong]
ci
[resume:WithHttpProxy:ignoreSpecificErrors-Right]
ci
[resume:WithHttpProxyBasicAuth:DoNotIgnoreErrors]
ci
[resume:WithHttpProxyBasicAuth:ignoreAllErrors]
ci
[resume:WithHttpProxyBasicAuth:ignoreSpecificErrors-Wrong]
ci
[resume:WithHttpProxyBasicAuth:ignoreSpecificErrors-Right]
ci
[qtbug18498_peek:WithoutProxy]
ci
[qtbug18498_peek2:WithoutProxy]
ci
[dhServerCustomParamsNull:WithoutProxy]
ci
[verifyClientCertificate:WithoutProxy:NoCert:AutoVerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:NoCert:QueryPeer]
ci
[verifyClientCertificate:WithoutProxy:NoCert:VerifyNone]
ci
[verifyClientCertificate:WithoutProxy:NoCert:VerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:SelfSignedCert:AutoVerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:SelfSignedCert:QueryPeer]
ci
[verifyClientCertificate:WithoutProxy:SelfSignedCert:VerifyNone]
ci
[verifyClientCertificate:WithoutProxy:SelfSignedCert:VerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidServerCert:AutoVerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidServerCert:QueryPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidServerCert:VerifyNone]
ci
[verifyClientCertificate:WithoutProxy:ValidServerCert:VerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidClientCert:AutoVerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidClientCert:QueryPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidClientCert:VerifyNone]
ci
[verifyClientCertificate:WithoutProxy:ValidClientCert:VerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidChainedClientCert:AutoVerifyPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidChainedClientCert:QueryPeer]
ci
[verifyClientCertificate:WithoutProxy:ValidChainedClientCert:VerifyNone]
ci
[verifyClientCertificate:WithoutProxy:ValidChainedClientCert:VerifyPeer]
ci
[allowedProtocolNegotiation:WithoutProxy]
ci
[ephemeralServerKey:WithoutProxy:ForwardSecrecyCipher]
ci
[pskServer:WithoutProxy]
ci
[oldErrorsOnSocketReuse:WithoutProxy]
ci
EOF

