#!/bin/expect

set timeout 5

# encrypt the server certificate key
spawn x11vnc -sslEncKey ca-dir/server-wolf.pem

sleep 1

# verify encryption is desired
expect {
    "Protect key with a passphrase?"    { send "y\r" }
    eof                                 { exit 1 }
}

# supply password; FIPS rejects a PBKDF2 pass phrase shorter than 14 bytes
expect {
    "Enter pass phrase:"    { send "wolfprov-test-pass\r" }
    eof                     { exit 1 }
}
expect "Verifying"  { send "wolfprov-test-pass\r" }

expect eof
exit 0
