name: Bind9 with wolfProvider

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wolfprovider:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4

      # Check if this version of wolfssl/wolfprovider has already been built,
      # mark to cache these items on post if we do end up building
      - name: Checking wolfSSL/wolfProvider in cache
        uses: actions/cache@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
          lookup-only: true

      # If wolfssl/wolfprovider have not yet been built, pull ossl from cache
      - name: Checking OpenSSL in cache
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install

          key: ossl-depends

      # If not yet built this version, build it now
      - name: Build wolfProvider
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        run: |
          WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      # Create an artifact as a fallback for when cache fails
      - name: Tar build directories for artifact
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        run: |
          tar -zcf wolfprov-build-${{ matrix.wolfssl_ref }}.tgz wolfssl-install wolfprov-install openssl-install provider.conf

      - name: Upload wolfProvider build
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: wolfprov-build-${{ matrix.wolfssl_ref }}
          path: wolfprov-build-${{ matrix.wolfssl_ref }}.tgz
          retention-days: 1

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi

  test_bind9:
    name: Test bind9 with wolfProvider
    needs: build_wolfprovider
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
        bind_ref: [ '9.18.0', '9.18.28' ]
    steps:
      # Either restore from cache or from artifact
      - name: Retrieving OpenSSL from cache
        uses: actions/cache/restore@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install

          key: ossl-depends
          fail-on-cache-miss: false

      # Restore the wolfssl/wolfprovider build from cache
      - name: Restore wolfSSL/wolfProvider from cache
        uses: actions/cache@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: false

      # If cache restore failed, download artifact
      - name: Download wolfProvider build
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: wolfprov-build-${{ matrix.wolfssl_ref }}

      - name: Extract wolfProvider build
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        run: |
          tar -xf wolfprov-build-${{ matrix.wolfssl_ref }}.tgz

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libuv1-dev libnghttp2-dev libcap-dev libcmocka-dev

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp

      - name: Checkout bind9
        uses: actions/checkout@v4
        with:
          repository: isc-projects/bind9
          path: bind9
          ref: v${{ matrix.bind_ref }}

      - name: Build and test bind9
        working-directory: bind9
        run: |
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib:$GITHUB_WORKSPACE/openssl-install/lib64
          export OPENSSL_CONF=$GITHUB_WORKSPACE/provider.conf
          export OPENSSL_MODULES=$GITHUB_WORKSPACE/wolfprov-install/lib
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib/pkgconfig
          patch -p1 < $GITHUB_WORKSPACE/osp/bind9/${{ matrix.bind_ref }}.patch
          autoreconf -ivf
          ./configure --with-wolfssl
          sed -i 's/SUBDIRS = system//g' bin/tests/Makefile # remove failing tests
          make -j$(nproc) V=1
          make -j$(nproc) V=1 check
