name: libhashkit2 Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]

  test_libhashkit2:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      matrix:
        libhashkit2_ref: [ 'v1.x', '1.1.4' ]
        wolfssl_ref: [ 'master', 'v5.8.0-stable' ]
        openssl_ref: [ 'openssl-3.5.0' ]
        force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
        exclude:
          - libhashkit2_ref: 'v1.x'
            force_fail: 'WOLFPROV_FORCE_FAIL=1'
    steps:
      # Checkout the source so we can run the check-workflow-result script
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
              .github
      - name: Retrieving OpenSSL from cache
        uses: actions/cache/restore@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install
          key: ossl-depends-${{ matrix.openssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Retrieving wolfSSL/wolfProvider from cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf
          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Install libmemcached dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake build-essential bison flex memcached libc6

      - name: Download libmemcached
        uses: actions/checkout@v4
        with:
          repository: awesomized/libmemcached
          ref: ${{ matrix.libhashkit2_ref }}
          path: libmemcached

      - name: Build libmemcached
        working-directory: libmemcached
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_OPENSSL_CRYPTO=ON ..
          make
          sudo make install

      - name: Run libhashkit2 tests
        working-directory: libmemcached/build
        run: |
          echo "Setting environment variables..."
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/wolfssl-install/lib:$GITHUB_WORKSPACE/openssl-install/lib64
          export OPENSSL_CONF=$GITHUB_WORKSPACE/provider.conf
          export OPENSSL_MODULES=$GITHUB_WORKSPACE/wolfprov-install/lib
          #export ${{ matrix.force_fail }}
          # Run tests
          make test 2>&1 | tee libhashkit2-test.log
          TEST_RESULT=${PIPESTATUS[0]}
          echo "TEST_RESULT = $TEST_RESULT"
          echo "Checking OpenSSL providers:"
          $GITHUB_WORKSPACE/openssl-install/bin/openssl list -providers | tee provider-list.log
          grep libwolfprov provider-list.log || (echo "ERROR: libwolfprov not found in OpenSSL providers" && exit 1)
          #$GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} libp11
