name: OpenSSL Version Tests

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  discover_versions:
    uses: ./.github/workflows/_discover-versions.yml

  openssl_version_test:
    needs: discover_versions
    name: OpenSSL Version Test
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        wolfssl_ref: ${{ fromJson(needs.discover_versions.outputs.wolfssl_latest_ref_array) }}
        openssl_ref: ${{ fromJson(needs.discover_versions.outputs.openssl_all_releases_array) }}
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and test wolfProvider
        run: |
          OPENSSL_TAG=${{ matrix.openssl_ref }} \
          WOLFSSL_TAG=${{ matrix.wolfssl_ref }} \
            ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi
