name: sssd Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4

      - name: Build wolfProvider
        run: |
          WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: tar build files
        run: |
          tar -zcf provider-build.tgz wolfssl-install wolfprov-install provider.conf openssl-source openssl-install

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: wolfprov-install-sssd
          path: provider-build.tgz
          retention-days: 5

  sssd_check:
    strategy:
      matrix:
        ref: [ '2.9.1' ]
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    name: ${{ matrix.ref }}-${{ matrix.wolfssl_ref }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/sssd/ci-client-devel:ubuntu-latest
      env:
        LD_LIBRARY_PATH: /usr/local/lib
    timeout-minutes: 20
    needs: build_wolfprovider
    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf libldb-dev libldb2 python3-ldb bc

      - name: Setup env
        run: |
          ln -s samba-4.0/ldb.h /usr/include/ldb.h
          ln -s samba-4.0/ldb_errors.h /usr/include/ldb_errors.h
          ln -s samba-4.0/ldb_handlers.h /usr/include/ldb_handlers.h
          ln -s samba-4.0/ldb_module.h /usr/include/ldb_module.h
          ln -s samba-4.0/ldb_version.h /usr/include/ldb_version.h

      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: wolfprov-install-sssd

      - name: untar build files
        run: tar -xf provider-build.tgz

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp

      - name: Build and test sssd
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: SSSD/sssd
          ref: ${{ matrix.ref }}
          path: sssd
          patch-file: $GITHUB_WORKSPACE/osp/sssd/${{ matrix.ref }}.patch
          configure: >-
            --without-samba --without-nfsv4-idmapd-plugin --with-oidc-child=no
            --without-manpages --without-pam-srv
            WOLFSSL_INSTALL_DIR=$GITHUB_WORKSPACE/wolfssl-install
            WOLFPROV_INSTALL_DIR=$GITHUB_WORKSPACE/wolfprov-install
          check: true
