name: SSSD Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    name: Build wolfProvider
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    steps:
      - name: Checkout wolfProvider
        uses: actions/checkout@v4

      # Check if this version of wolfssl/wolfprovider has already been built,
      # mark to cache these items on post if we do end up building
      - name: Checking wolfSSL/wolfProvider in cache
        uses: actions/cache@v4
        id: wolfprov-cache
        with:
          path: |
            wolfssl-source
            wolfssl-install
            wolfprov-install
            provider.conf

          key: wolfprov-${{ matrix.wolfssl_ref }}-${{ github.sha }}
          lookup-only: true

      # If wolfssl/wolfprovider have not yet been built, pull ossl from cache
      - name: Checking OpenSSL in cache
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        id: openssl-cache
        with:
          path: |
            openssl-source
            openssl-install

          key: ossl-depends
          fail-on-cache-miss: false

      # If not yet built this version, build it now
      - name: Build wolfProvider
        if: steps.wolfprov-cache.outputs.cache-hit != 'true'
        run: |
          WOLFSSL_TAG=${{ matrix.wolfssl_ref }} ./scripts/build-wolfprovider.sh

      - name: Print errors
        if: ${{ failure() }}
        run: |
          if [ -f test-suite.log ] ; then
            cat test-suite.log
          fi

      # Create a tarball of the build artifacts for use in the container
      - name: Create tarball of build artifacts
        run: |
          tar -zcf wolfprov-artifacts.tgz wolfssl-source wolfssl-install wolfprov-install provider.conf openssl-source openssl-install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wolfprov-artifacts-${{ matrix.wolfssl_ref }}
          path: wolfprov-artifacts.tgz
          retention-days: 5

  test_sssd:
    runs-on: ubuntu-22.04
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # List of releases to test
        ref: [ 2.9.1 ]
        wolfssl_ref: [ 'master', 'v5.7.4-stable' ]
    container:
      image: quay.io/sssd/ci-client-devel:ubuntu-latest
      env:
        LD_LIBRARY_PATH: /usr/local/lib:/github/home/wolfssl-install/lib:/github/home/openssl-install/lib64
    steps:
      - name: Install dependencies
        run: |
          # Don't prompt for anything
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y build-essential autoconf libldb-dev libldb2 python3-ldb bc

      - name: Setup env
        run: |
          ln -s samba-4.0/ldb.h /usr/include/ldb.h
          ln -s samba-4.0/ldb_errors.h /usr/include/ldb_errors.h
          ln -s samba-4.0/ldb_handlers.h /usr/include/ldb_handlers.h
          ln -s samba-4.0/ldb_module.h /usr/include/ldb_module.h
          ln -s samba-4.0/ldb_version.h /usr/include/ldb_version.h

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wolfprov-artifacts-${{ matrix.wolfssl_ref }}
          path: /github/home

      - name: Extract artifacts
        working-directory: /github/home
        run: |
          tar -xf wolfprov-artifacts.tgz
          ls -la

      - name: Checkout OSP
        uses: actions/checkout@v4
        with:
          repository: wolfssl/osp
          path: osp

      - name: Build sssd with wolfProvider
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          repository: SSSD/sssd
          ref: ${{ matrix.ref }}
          path: sssd
          patch-file: $GITHUB_WORKSPACE/osp/sssd/${{ matrix.ref }}.patch
          configure: >-
            --without-samba --without-nfsv4-idmapd-plugin --with-oidc-child=no
            --without-manpages OPENSSL_INSTALL_DIR=/github/home/openssl-install
          check: true
